include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - avoid_print: true
    - prefer_const_constructors: true
    - prefer_const_declarations: true
    - avoid_empty_else: true
    - use_key_in_widget_constructors: true

analyzer:
  errors:
    todo: info